# Training Logic Gate Ouputs Using Neural Networks

## Imports

In [1]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras import Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import BinaryCrossentropy
import pandas as pd
import numpy as np

## Training 3 Input AND Gate

In [2]:
X_train = np.array([[1, 1, 1], [1, 1, 1],[1, 1, 1],[1, 1, 0], [1, 0, 1], [1, 0, 0], [0, 1, 1], [0, 1, 0]])
Y_train = np.array([1, 1, 1, 0, 0, 0, 0, 0])

print(f"Input training data: \n{X_train}")
print(f"Output training data: {Y_train}")
print(X_train.shape)
print(Y_train.shape)

Input training data: 
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 0]
 [1 0 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]]
Output training data: [1 1 1 0 0 0 0 0]
(8, 3)
(8,)


In [26]:
model_AND = Sequential([
    Input(shape=(3,)),
    Dense(units=10, input_dim=3, activation='relu'),
    Dense(units=8, activation='relu'),
    Dense(units=1, activation='sigmoid')
])

model_AND.compile(optimizer=Adam(), loss=BinaryCrossentropy())
model_AND.summary()

c:\ProgramData\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                │ (None, 10)             │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 137 (548.00 B)

 Trainable params: 137 (548.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
model_AND.fit(X_train, Y_train, epochs=1000)

Epoch 1/1000


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.6834
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.6815
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.6796
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.6777
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.6758
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.6739
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.6721
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.6702
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6683
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.6666
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.6651
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.6636
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6621
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.6606
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.6590
Epoch 16/1000
1/1 ━

In [28]:
X_test = np.array([[0, 0, 1], [0, 0, 0], [1, 1, 1]])

predictions = model_AND.predict(X_test)
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step


array([[8.4218185e-04],
       [1.4064923e-03],
       [9.9403852e-01]], dtype=float32)

In [29]:
Y_test = np.zeros(3)
for x in range(3):
    if predictions[x] >= 0.5:
        Y_test[x] = 1
    else:
        Y_test[x] = 0

print(Y_test)


[0. 0. 1.]


## 3 Input OR Gate

In [7]:
OR_input = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1]])
OR_output = np.array([0, 1, 1, 1, 1, 1])

print(OR_input.shape)
print(OR_output.shape)

(6, 3)
(6,)


In [21]:
or_network = Sequential([
    Input(shape=(3,)),
    Dense(units=10, activation='relu'),
    Dense(units=8, activation='relu'),
    Dense(units=1, activation='sigmoid'),
])

or_network.compile(optimizer=Adam(), loss=BinaryCrossentropy())
or_network.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 10)             │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 137 (548.00 B)

 Trainable params: 137 (548.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
or_network.fit(OR_input, OR_output, epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0889
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0888
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0888
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.0887
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0887
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0886
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0886
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0885
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0885
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0884
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0884
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0883
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0883
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0882
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0882
Epoc

In [24]:
or_test = np.array([[1, 1, 0], [1, 1, 1], [0, 0, 0]])

or_predictions = or_network.predict(or_test)
or_predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step


array([[0.9999998 ],
       [1.        ],
       [0.25728348]], dtype=float32)

In [31]:
or_test = np.zeros(3)
for x in range(len(or_predictions)):
    if or_predictions[x] >= 0.5:
        or_test[x] = 1
    else:
        or_test[x] = 0

print(or_test)

[1. 1. 0.]


## XOR Gate

In [39]:
xor_input = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
xor_output = np.array([0, 1, 1, 0, 1, 0, 0, 1])

print(f"Input Shape: {xor_input.shape}")
print(f"Output Shape: {xor_output.shape}")

Input Shape: (8, 3)
Output Shape: (8,)


In [40]:
xor_network = Sequential([
    Input(shape=(3,)),
    Dense(units=10, activation='relu'),
    Dense(units=8, activation='relu'),
    Dense(units=1, activation='sigmoid'),
])

xor_network.compile(optimizer=Adam(), loss=BinaryCrossentropy())
xor_network.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_24 (Dense)                │ (None, 10)             │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_26 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 137 (548.00 B)

 Trainable params: 137 (548.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
xor_network.fit(xor_input, xor_output, epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.6886
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.6880
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.6873
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.6866
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.6859
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.6852
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.6845
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.6838
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.6831
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.6825
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.6818
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.6811
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.6805
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 0.6798
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.6791
Epoch 

In [46]:
xor_predict = np.array([[1, 1, 0], [1, 1, 1]])

xor_predictions = xor_network.predict(xor_predict)
xor_predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[0.03216474],
       [0.9683342 ]], dtype=float32)

In [52]:
xor_final = np.zeros(2)
for x in range(len(xor_predictions)):
    if xor_predictions[x] >= 0.5:
        xor_final[x] = 1
    else:
        xor_final[x] = 0

xor_final

array([0., 1.])